spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nir_database
    username: postgres
    password: Iissupe5
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  application:
    name : project
  thymeleaf:
    templates_root: src/main/resources/templates/
    prefix: classpath:/templates/

gigachat:
  client:
    id: 2bb5f523-726d-432e-baf5-f7f49f71e50d
    scope: GIGACHAT_API_PERS
    secret: a09a41a4-9caa-4cd5-836d-7a0ee4ac74fd

